baseURL: https://samlj.netlify.app/
title: Sam's Site
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  avatar: "avatar.jpg"
  author: Samuel Johnson
  description: Linguist, Language Instructor, Analyst
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/Mexicajun1605
    - icon: linkedin
      name: Linkedin
      url: https://www.linkedin.com/in/samuel-johnson-b9263622a/
    - icon: youtube
      name: Youtube
      url: https://www.youtube.com/channel/UCpOnqfVILHIOUKhW5BiEEnQ
